# Generated by Django 2.0.1 on 2018-01-29 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookinfo',
            table='bookinfo',
        ),
    ]
