# Generated by Django 2.0.1 on 2018-01-30 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('pwd', models.CharField(max_length=20)),
                ('email', models.CharField(default='', max_length=20)),
                ('address', models.CharField(default='', max_length=40)),
                ('phone', models.CharField(default='', max_length=11)),
                ('youbian', models.CharField(default='', max_length=7)),
            ],
        ),
    ]
